version: "3.8"
services:
  springboot-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: springboot-container
    ports:
      - "8080:8081"  # Exposes the Spring Boot application on port 8080
    depends_on:
      - postgres     # Ensures PostgreSQL starts before Spring Boot
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/app_db
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_password
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Initializes the DB with SQL script
    ports:
      - "5436:5432"
    networks:
      - app-network

volumes:
  postgres-data:  # Persistent volume for PostgreSQL data
networks:
  app-network:
    driver: bridge